#!/bin/bash

# =============================================================================
# Fun Fact: we can use the following shebang line for cross-compiling:
# /* #!/bin/sh; C:/Program\ Files/path/to/Git/usr/bin/sh.exe */
# according to https://www.youtube.com/watch?v=fMYv6-SZsSo
# =============================================================================

# ============================================================================
# Script setup
# ============================================================================

# navigate to project root directory
git_dir=$(git rev-parse --show-toplevel)
cd $git_dir 1>pre-push.log
# add logger to the scope
source $(pwd)/tools/scripts/utils/logger.sh

log_info "Running pre-push hook..."

# =============================================================================
# Assert that git user's email is valid (under the company's domain)
# =============================================================================

# change `domain` to use your company's domain
domain="outlook.com"
usermail=$(git config user.email)
if [[ "$usermail" != *"@$domain" ]]; then
    log_fatal "Invalid username: $usermail! Please config git to use your company's email address."
    exit 1
fi

# We could also check if the username is within a list of names

# =============================================================================
# Clean
# =============================================================================

log_warn "Saving to stash"
git stash -u

# =============================================================================
# Run All Tests With Clean Build
# =============================================================================

$(pwd)/tools/scripts/utils/runTests.sh -f
if [[ "$?" != 0 ]]; then
    log_error "pre-push tests - FAILED"
    exit 1
else
    log_info "pre-push tests - DONE"
fi

# =============================================================================
# Clean up
# =============================================================================

# return to previous cwd
cd - 1> pre-push.log
rm pre-push.log

GIT_STASH_LIST=`git stash list`
if [[ "$GIT_STASH_LIST" != "" ]]; then
    log_warn "Loading from stash"
    git stash pop
fi
